#!/usr/bin/env bash
#############################################################################
# RunFlexSpec
# /home/git/external/FlexSpec1/Code/FlexSpec/UserInterface/RunFlexSpec
# bokeh serve ./FlexSpec.py --unused-session-lifetime 3600000
# uses: /home/git/external/FlexSpec1/Code/SBC/server.py
#############################################################################

__version="0.0.1"

function usage {
   echo "Version $__version"
   echo "RunFlexSpec ... switches"
   echo "  -t <intervaltime> in microseconds 3600000 is one hour."
   echo "  -s - use show flag with bokeh."
   echo "  -v - pass verbose flag to FlexSpec."
   echo "  -h - show help an quit."
   echo "Run the $__version spectrograph interface."
   echo "Hint: ps aux | grep RunFlexSpec; # and kill -9 the pid as needed."
   echo "sudo ss -lptn 'sport = :5006' # find pid for a port to kill -9"
}

mswitch=""
intervaltime="3600000"
verboseflag=""
showflag=""
currpid=""

sigint_handler()
{
   if [ "$currpid" != ""];  then kill -i "$pid"; fi
   echo "RunFlexSpec: Terminated $pid."
}

trap sigint_handler SIGINT


# leading colon is silent. ":hb:" h has no option, b has an option.
while getopts ":hsvt:" opt ; do     # request to use master bib
   case $opt in
   h)
      usage
      exit 1
      ;; # process a two part parm
   s)
       showeflag="show"
      ;;
   v)
      verboseflag="-v"
      ;;
   t)
       intervaltime=${OPTARG}
      ;;
   esac
done

../../SBC/server.py "$verboseflag" &

# Finally! The command we want to run.
currpid=$(echo $$; exec bokeh serve $show ./FlexSpec.py $mswitch --unused-session-lifetime $intervaltime)
